name: Unassign Issue After 7 days
on:
  schedule:
    - cron: '0 0 * * *' ### Runs everyday at 00h

jobs:
  unassign-issues-labeled-waiting-for-contributor-after-7-days-of-inactivity:
    name: Unassign issues after 7 days of inactivity.
    runs-on: ubuntu-latest
    steps:
      - uses: boundfoxstudios/action-unassign-contributor-after-days-of-inactivity@main
        with:
          last-activity: 7 # After how many days the issue should get unassigned ()
          message: 'Automatically unassigned after 7 days of inactivity.'
